
//All data-action attributes in the app
//We stored this list in an object to make it easier adding and deleting values,
//so we don't have to access them by their index
export const activityList = {
    "open-change-voting-rate": "open-change-voting-rate",
    "change-voting-rate": "change-voting-rate",
    "generate-ai-video": "generate-ai-video",
    "download-ai-video": "download-ai-video",
    "preview-ai-video": "preview-ai-video",
    "open-app": "open-app",
    "clear-signature": "clear-signature",
    "download-signature": "submit-signature",
    "submit-signature": "submit-signature",
    "app-scroll-down": "app-scroll-down",
    "close-alert": "close-alert",
    "fold-menu":"fold-menu",
    "unfold-menu":"unfold-menu",
    "logout":"logout",
    "menu-SM_stats":"menu-SM_stats",
    "menu-Raw_Data":"menu-Raw_Data",
    "menu-Ranking":"menu-Ranking",
    "menu-CallCenter":"menu-CallCenter",
    "menu-CallCenterHistory":"menu-CallCenterHistory",
    "menu-ElectionDay":"menu-ElectionDay",
    "menu-Volunteer":"menu-Volunteer",
    "menu-opponnents":"menu-opponnents",
    "menu-Users":"menu-Users",
    "menu-Settings":"menu-Settings",
    "menu-connections":"menu-connections",
    "pagination-prev": "pagination-prev",
    "pagination-change": "pagination-change",
    "pagination-next": "pagination-next",
    "notification-file-download": "notification-file-download",
    "notification-delete": "notification-delete",
    "change-lang": "change-lang",
    "toggle-hint": "toggle-hint",
    "toggle-hint-page": "toggle-hint-page",
    "warning-refuse": "warning-refuse",
    "warning-confirm": "warning-confirm",
    "close-modal": "close-modal",
    "open-bug_report": "open-bug_report",
    "send-bug_report": "send-bug_report",
    "stats-sreenshot": "stats-sreenshot",
    "post-preview-link": "post-preview-link",
    "open-map-upload": "open-map-upload",
    "map-template-download": "map-template-download",
    "map-data-upload": "map-data-upload",
    "map-data-submit": "map-data-submit",
    "update-status-data": "update-status-data",
    "status-hint": "status-hint",
    "raw-data-filters-hint": "raw-data-filters-hint",

    "raw-data-digital-campaign-opened":"raw-data-digital-campaign-opened",
    "raw-data-offline-campaign-opened":"raw-data-offline-campaign-opened",
    "raw-data-digital-campaign-sms":"raw-data-digital-campaign-sms",
    "raw-data-digital-campaign-emails":"raw-data-digital-campaign-emails",
    "raw-data-digital-campaign-facebook-ads":"raw-data-digital-campaign-facebook-ads",
    "raw-data-digital-campaign-google-ads":"raw-data-digital-campaign-google-ads",
    "raw-data-digital-campaign-sms-next":"raw-data-digital-campaign-sms-next",
    "raw-data-digital-campaign-sms-prev":"raw-data-digital-campaign-sms-prev",
    "raw-data-digital-campaign-sms-create":"raw-data-digital-campaign-sms-create",

    "raw-data-digital-campaign-emails-next":"raw-data-digital-campaign-emails-next",
    "raw-data-digital-campaign-emails-prev":"raw-data-digital-campaign-emails-prev",
    "raw-data-digital-campaign-emails-create":"raw-data-digital-campaign-emails-create",
    "raw-data-digital-campaign-facebook-del":"raw-data-digital-campaign-facebook-del",
    "raw-data-digital-campaign-facebook-create":"raw-data-digital-campaign-facebook-create",

    "filters-apply": "filters-apply",
    "create-audience": "create-audience",
    "configure-audience":"configure-audience",
    "open-strategic-report": "open-strategic-report",
    "rawdata-summarization-report": "rawdata-summarization-report",
    "request-strategic-report": "request-strategic-report",
    "export-facebook-csv": "export-facebook-csv",
    "open-export-facebook-csv": "open-export-facebook-csv",
    "clear-filters": "clear-filters",
    "rawdata-update-stats": "rawdata-update-stats",
    "rawdata-status-hint": "rawdata-status-hint",
    "rawdata-add-row": "rawdata-add-row",
    "rawdata-add-institution": "rawdata-add-institution",
    "rawdata-row-edit": "rawdata-row-edit",
    "rawdata-row-create": "rawdata-row-create",
    "rawdata-download-table": "rawdata-download-table",
    "rawdata-upload-table": "rawdata-upload-table",
    "rawdata-download-template": "rawdata-download-template",
    "rawdata-excel-submit": "rawdata-excel-submit",
    "rawdata-update-manually": "rawdata-update-manually",
    "rawdata-download-pivot": "rawdata-download-pivot",
    "rawdata-update-add_field": "rawdata-update-add_field",
    "rawdata-update-by_file": "rawdata-update-by_file",
    "rawdata-update-by_ids": "rawdata-update-by_ids",
    "rawdata-update-by_filters": "rawdata-update-by_filters",
    "rawdata-update-template": "rawdata-update-template",
    "rawdata-update-submit": "rawdata-update-submit",
    "table-reset-sorting": "table-reset-sorting",
    "table-set-sorting": "table-set-sorting",
    "table-payment": "table-payment",
    "table-delete": "table-delete",
    "table-edit": "table-edit",
    "table-row-files": "table-row-files",
    "table-row-change-status": "table-row-change-status",
    "download-row-files": "download-row-files",
    "download-row-file": "download-row-file",
    "rawdata-open-modelling": "rawdata-open-modelling",
    "rawdata-select-field": "rawdata-select-field",
    "rawdata-modelling-run": "rawdata-modelling-run",
    "rawdata-open-clustering": "rawdata-open-clustering",
    "rawdata-clustering-run": "rawdata-clustering-run",
    "rawdata-open-families_grouping": "rawdata-open-families_grouping",
    "rawdata-families_id-update": "rawdata-families_id-update",


    "rankings-filters-apply": "rankings-filters-apply",
    "rankings-filters-clear": "rankings-filters-clear",
    "rankings-suggest-AIpost": "rankings-suggest-AIpost",
    "rankings-generate-AIpost": "rankings-generate-AIpost",
    "rankings-cancel-AIpost": "rankings-cancel-AIpost",
    "rankings-clear-selected-posts": "rankings-clear-selected-posts",
    "rankings-AIpicture-V1": "rankings-AIpicture-V1",
    "rankings-AIpicture-V2": "rankings-AIpicture-V2",
    "rankings-AIpicture-V3": "rankings-AIpicture-V3",
    "rankings-AIpicture-V4": "rankings-AIpicture-V4",
    "rankings-AIpicture-U1": "rankings-AIpicture-U1",
    "rankings-AIpicture-U2": "rankings-AIpicture-U2",
    "rankings-AIpicture-U3": "rankings-AIpicture-U3",
    "rankings-AIpicture-U4": "rankings-AIpicture-U4",
    "rankings-AIpicture-resize": "rankings-AIpicture-resize",
    "rankings-AIhistory-open": "rankings-AIhistory-open",
    "defamatory-report": "defamatory-report",
    "toggle-monitoring-filters": "toggle-monitoring-filters",
    "select-tag_cloud": "select-tag_cloud",
    "create-topic-keyword": "create-topic-keyword",
    "open-edit-score": "open-edit-score",
    "edit-post-score": "edit-post-score",
    "decline-keyword": "decline-keyword",
    "delete-post-keyword": "delete-post-keyword",
    "open-institutions": "open-institutions",
    "track-notorious-user": "track-notorious-user",
    "set-post-processed": "set-post-processed",
    "download-post-screenshot": "download-post-screenshot",
    "add-post-to-googlesheets": "add-post-to-googlesheets",
    "add-post-to-botfarm": "add-post-to-botfarm",
    "select-trending-post": "select-trending-post",
    "delete-publication": "delete-publication",
    "delete-post": "delete-post",
    "delete-post-author": "delete-post-author",
    "open-publication-link": "open-publication-link",
    "open-publication-source": "open-publication-source",
    "publication-processed": "publication-processed",
    "call-center-hint": "call-center-hint",
    "call-center-sms": "call-center-sms",
    "call-center-calls": "call-center-calls",
    "call-center-emails": "call-center-emails",
    "call-center-next-interviewer":"call-center-next-interviewer",
    "call-center-social": "call-center-social",
    "call-center-google": "call-center-google",
    "call-center-email_send": "call-center-email_send",
    "call-center-email_test": "call-center-email_test",
    "call-center-sms_send": "call-center-sms_send",
    "call-center-sms_test": "call-center-sms_test",
    "call-center-questionnaire_send": "call-center-questionnaire_send",
    "call-center-call": "call-center-call",
    "call-center-no_answer": "call-center-no_answer",
    "call-center-FB-ad_delete": "call-center-FB-ad_delete",
    "call-center-FB-ad_create": "call-center-FB-ad_create",
    "call-center-FB-campaign_create": "call-center-FB-campaign_create",
    "call-center-FB-set_create": "call-center-FB-set_create",
    "call-center-FB-audience_filter": "call-center-FB-audience_filter",
    "call-center-FB-audience_fans": "call-center-FB-audience_fans",
    "call-center-FB-audience_campaign": "call-center-FB-audience_campaign",
    "call-center-FB-audience_filter_create": "call-center-FB-audience_filter_create",
    "call-center-FB-audience_page_create": "call-center-FB-audience_page_create",
    "call-center-FB-audience_campaign_create": "call-center-FB-audience_campaign_create",
    "call-center-FB-creative_create":  "call-center-FB-creative_create",
    "call-center-FB-ad_modal_create": "call-center-FB-ad_modal_create",
    "call-center-google-campaign_modal": "call-center-google-campaign_modal",
    "call-center-google-campaign_create": "call-center-google-campaign_create",
    "call-center-google-criteria_create": "call-center-google-criteria_create",
    "call-center-google-group_modal": "call-center-google-group_modal",
    "call-center-google-group_create": "call-center-google-group_create",
    "call-center-google-group_clear": "call-center-google-group_clear",
    "call-center-google-group_criteria_create": "call-center-google-group_criteria_create",
    "call-center-google-group_criteria_clear": "call-center-google-group_criteria_clear",
    "call-center-google-ad_modal": "call-center-google-ad_modal",
    "call-center-google-ad_create": "call-center-google-ad_create",
    "call-center-google-ad_clear": "call-center-google-ad_clear",
    "call-center-google-audience_clear":  "call-center-google-audience_clear",
    "call-center-google-audience_create":  "call-center-google-audience_create",
    //Reports
    "reports-select-outgoing-sms": "reports-select-outgoing-sms",
    "reports-select-incoming-sms": "reports-select-incoming-sms",
    "reports-select-call-center": "reports-select-call-center",
    "reports-select-edits": "reports-select-edits",
    "reports-select-activity": "reports-select-activity",
    "reports-outgoing-sms-download": "reports-outgoing-sms-download",
    "reports-outgoing-sms-apply": "reports-outgoing-sms-apply",
    "reports-outgoing-sms-clear": "reports-outgoing-sms-clear",
    "reports-outgoing-sms-sort": "reports-outgoing-sms-sort",
    "reports-outgoing-sms-scroll": "reports-outgoing-sms-scroll",
    "reports-incoming-sms-download": "reports-incoming-sms-download",
    "reports-incoming-sms-apply": "reports-incoming-sms-apply",
    "reports-incoming-sms-clear": "reports-incoming-sms-clear",
    "reports-incoming-sms-sort": "reports-incoming-sms-sort",
    "reports-incoming-sms-scroll": "reports-incoming-sms-scroll",
    "reports-emails-download": "reports-emails-download",
    "reports-emails-apply": "reports-emails-apply",
    "reports-emails-clear": "reports-emails-clear",
    "reports-emails-sort": "reports-emails-sort",
    "reports-emails-scroll": "reports-emails-scroll",
    "reports-questionnaires-download": "reports-questionnaires-download",
    "reports-app-download": "reports-app-download",
    "reports-questionnaires-apply": "reports-questionnaires-apply",
    "reports-questionnaires-clear": "reports-questionnaires-clear",
    "reports-voter-apply": "reports-voter-apply",
    "reports-voter-clear": "reports-voter-clear",

    "reports-questionnaires-sort": "reports-questionnaires-sort",
    "reports-app-sort": "reports-app-sort",
    "reports-questionnaires-scroll": "reports-questionnaires-scroll",
    "reports-app-scroll": "reports-app-scroll",
    "reports-edits-download": "reports-edits-download",
    "reports-edits-apply": "reports-edits-apply",
    "reports-edits-clear": "reports-edits-clear",
    "reports-edits-sort": "reports-edits-sort",
    "reports-edits-scroll": "reports-edits-scroll",
    "reports-activity-apply": "reports-activity-apply",
    "reports-activity-clear": "reports-activity-clear",
    "reports-activity-download": "reports-activity-download",
    "reports-activity-sort": "reports-activity-sort",
    "reports-activity-scroll": "reports-activity-scroll",
    "election-kpi-clear": "election-kpi-clear",
    "election-table-reset_sort": "election-table-reset_sort",
    "election-table-sort": "election-table-sort",
    "election-table-scroll": "election-table-scroll",
    "volunteers-craete-task": "volunteers-craete-task",
    "volunteers-assign-task": "volunteers-assign-task",
    "volunteers-filters-apply": "volunteers-filters-apply",
    "volunteers-filters-clear": "volunteers-filters-clear",
    "volunteers-table-scroll": "volunteers-table-scroll",
    "volunteers-table-download": "volunteers-table-download",
    "volunteers-table-delete": "volunteers-table-delete",
    "opponents-reset": "opponents-reset",
    "opponents-search": "opponents-search",
    "opponents-delete": "opponents-delete",
    "opponents-select_preferred": "opponents-select_preferred",
    "opponents-preferred_no": "opponents-preferred_no",
    "opponents-preferred_yes": "opponents-preferred_yes",
    "opponents-select-not_preferred": "opponents-select-not_preferred",
    "opponents-search-yes": "opponents-search-yes",
    "opponents-search-no": "opponents-search-no",
    "users-sort-table": "users-sort-table",
    "users-bulk-delete": "users-bulk-delete",
    "users-create-modal": "users-create-modal",
    "users-edit-modal": "users-edit-modal",
    "users-delete-user": "users-delete-user",
    "users-change-selected": "users-change-selected",
    "users-scroll-table": "users-scroll-table",
    "users-save-user": "users-save-user",
    "connections-filter-apply": "connections-filter-apply",
    "connections-filter-clear": "connections-filter-clear",
    "relations-refresh": "relations-refresh",
    "settings-privacy-policy": "settings-privacy-policy",
    "settings-distribution-open": "settings-distribution-open",
    "settings-modules-open": "settings-modules-open",
    "settings-general-open": "settings-general-open",
    "settings-post_types-open": "settings-post_types-open",
    "settings-post_types-save": "settings-post_types-save",
    "settings-sms-toggle": "settings-sms-toggle",
    "existing-sms-save": "existing-sms-save",
    "new-sms-save": "new-sms-save",
    "settings-email-toggle": "settings-email-toggle",
    "existing-email-save": "existing-email-save",
    "new-email-save": "new-email-save",
    "settings-distribution-toggle": "settings-distribution-toggle",
    "clear-injected-users": "clear-injected-users",
    "inject-users-app": "inject-users-app",
    "questionnaire-users-mapping": "questionnaire-users-mapping",
    "questionnaire-audience-mapping": "questionnaire-audience-mapping",
    "audience-users-mapping": "audience-users-mapping",
    "toggle-mapping": "toggle-mapping",
    "toggle-users-count": "toggle-users-count",
    "increase-users-count": "increase-users-count",
    "decrease-users-count": "decrease-users-count",
    "users-count-save": "users-count-save",
    "clear-audiences-filters": "clear-audiences-filters",
    "audiences-delete": "audiences-delete",
    "audiences-add": "audiences-add",
    "audiences-update": "audiences-update",
    "questionnaires-toggle": "questionnaires-toggle",
    "questionnaires-delete": "questionnaires-delete",
    "questionnaires-edit-name": "questionnaires-edit-name",
    "questionnaires-clone": "questionnaires-clone",
    "questionnaires-save-name": "questionnaires-save-name",
    "question-change-order": "question-change-order",
    "field-change-order": "field-change-order",
    "question-delete": "question-delete",
    "question-edit": "question-edit",
    "question-toggle-answers": "question-toggle-answers",
    "save-editing-question": "save-editing-question",
    "editing-question-reset": "editing-question-reset",
    "add-question": "add-question",
    "add-answer": "add-answer",
    "edit-answer": "edit-answer",
    "delete-answer": "delete-answer",
    "save-editing-answer": "save-editing-answer",
    "settings-add-payment": "settings-add-payment",
    "settings-generate-sentiment-prompt":"settings-generate-sentiment-prompt",
    "settings-add-email": "settings-add-email",
    "settings-edit-sentiment-prompt":"settings-edit-sentiment-prompt",
    "open-edit-pages": "open-edit-pages",
    "settings-pages-save": "settings-pages-save",
    "toggle-voter": "toggle-voter",
    "disconnect-voter-agree": "disconnect-voter-agree",
    "disconnect-voter-refuse": "disconnect-voter-refuse",
    "toggle-facebook-connection": "toggle-facebook-connection",
    "toggle-google-connection": "toggle-google-connection",
    "toggle-election-day": "toggle-election-day",
    "toggle-volunteers-module": "toggle-volunteers-module",
    "open-edit-fields": "open-edit-fields",
    "open-sentiment-definition":"open-sentiment-definition",
    "settings-create-field":  "settings-create-field",
    "settings-edit-field":  "settings-edit-field",
    "settings-delete-field":  "settings-delete-field",
    "open-status-settings": "open-status-settings",
    "settings-create-status": "settings-create-status",
    "settings-delete-status": "settings-delete-status",
    "settings-statuses-save": "settings-statuses-save",
    "open-create-status": "open-create-status",
    "open-edit-segments": "open-edit-segments",
    "create-segment": "create-segment",
    "edit-segment": "edit-segment",
    "bind-segment-keyword": "bind-segment-keyword",
    "delete-segment": "delete-segment",
    "delete-segment-with_keywords": "delete-segment-with_keywords",
    "delete-segment-keyword": "delete-segment-keyword",
    "unbind-segment-keyword": "unbind-segment-keyword",
    "settings-add-signature": "settings-add-signature",
    "settings-delete-signature": "settings-delete-signature",
    "settings_bug_report": "settings_bug_report",
    "open-inject-users-app": "open-inject-users-app",
    "open-voter-contact-mode": "open-voter-contact-mode",
    "voter-change-pass": "voter-change-pass",
    "voter-switch-mode": "voter-switch-mode",
    "voter-apply-questionnaire": "voter-apply-questionnaire",
    "voter-inject-audience": "voter-inject-audience",



    "open-voter-assignements": "open-voter-assignements",
    "voter-create-users": "voter-create-users",

    "open-voter-users-creating": "open-voter-users-creating",


    "switch-voter-notify-inject": "switch-voter-notify-inject",


    "settings-app-open": "settings-app-open",




    "settings-resync-contacts": "settings-resync-contacts",

    "monitoring-add-post": "monitoring-add-post",
    "monitoring-add-user": "monitoring-add-user",

    "monitoring-change-defamatory": "monitoring-change-defamatory",



    "ranking-change-post_type": "ranking-change-post_type",


    "ranking-delete-ai-post": "ranking-delete-ai-post",
    "ranking-regenerate-ai-post": "ranking-regenerate-ai-post",
    "ranking-upload-ai-post":"ranking-upload-ai-post",
    "settings-open-keywords-excel": "settings-open-keywords-excel",
    "settings-upload-keywords-excel": "settings-upload-keywords-excel",



    "ranking-add-keyword-to-post": "ranking-add-keyword-to-post",



    "ranking-toggle-summarization": "ranking-toggle-summarization",


    "ranking-create-summarization": "ranking-create-summarization",
    "ranking-delete-summarization": "ranking-delete-summarization",
    "ranking-clear-summarization": "ranking-clear-summarization",
    "ranking-summarize-summarization": "ranking-summarize-summarization",
    "ranking-assign-posts-summarization": "ranking-assign-posts-summarization",
    "ranking-clear-selected-summarization": "ranking-clear-selected-summarization",


    "settings-delete-voter-users": "settings-delete-voter-users",

























}
